name = "BaremetalPi"
uuid = "3a90a9a9-52f9-452b-94bd-193d585bd84f"
authors = ["Ronan Arraes Jardim Chagas <ronisbr@gmail.com>"]
version = "0.1.0"

[compat]
julia = "1"

[deps]
Mmap = "a63ad114-7e13-5084-954f-fe012c677804"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
